### ISSUE TITLE
Is tc0003a a valid test?

### ISSUE THREAD

**Issue by bcogrel** [kg-construct/r2rml-implementation-report#10]
Hi,

tc0003a ["tests the presence of an undefined SQL Version identifier"](https://github.com/kg-construct/r2rml-implementation-report/blob/main/test-cases/manifest.ttl#L191) and expects an error to be thrown.

In the mapping, one can find that `rr:SQL1979` is used as `rr:sqlVersion`.

In the [SQL version section](https://www.w3.org/TR/r2rml/#dfn-sql-version-identifier) of the R2RML specification, I have not seen any reference to a normative static list of valid SQL versions, nor to the error expected by this test. Have I missed something?

Is this test valid? Shall we discard it?

Best,
Benjamin

**Comment by dachafra** [comment]
There is a list of possible SQL Version identifiers here: https://www.w3.org/2001/sw/wiki/RDB2RDF/SQL_Version_IRIs but assuming that the spec claims _"The RDB2RDF Working Group intends to maintain a non-normative"_ the list may not be completed. 

As part of the work in the CG, shall we create that list? Shall we discard this test-case? @pheyvaer

**Comment by pheyvaer** [comment]
Indeed create the list and update this test case instead of discarding?

**Comment by dachafra** [comment]
we will provide a list inside the test-case folder in the form of a CSV file and we can also provide a link to it in the implementation report or language specification

**Comment by dachafra** [comment]
added with the info provided at  https://www.w3.org/2001/sw/wiki/RDB2RDF/SQL_Version_IRIs

https://github.com/kg-construct/r2rml-implementation-report/blob/main/test-cases/R2RMLTC0003a/sql_valid_iris.csv

**Comment by pheyvaer** [comment]
Can't we provide this list as RDF instead of CSV? 😄

**Comment by dachafra** [comment]
who propose it, will do it ;-) haha

**Comment by bcogrel** [comment]
Sorry but I don't understand how you would like to update this test. If nothing says in the standard that an unrecognized IRI for the SQL version must raise an error, what can we test?

I understand that an implementation may issue a warning when the IRI is not recognized, but I am not sure it is something we can consider in this test suite.

**Comment by pheyvaer** [comment]
@bcogrel Yeah indeed, that's a valid remark! Maybe we should discard it after all.

**Comment by dachafra** [comment]
so... finally do we have decided to discard it? I'm also in favor to do it, I don't think it's totally necessary for this kind of test-cases

**Comment by pheyvaer** [comment]
Indeed!

**Comment by dachafra** [comment]
removed, thanks for the help @bcogrel @pheyvaer!
