### ISSUE TITLE
Concatenation with MySQL

### ISSUE THREAD

**Issue by bcogrel** [kg-construct/r2rml-implementation-report#12]
The `||` operator is not supported by MySQL . See [this example](https://dbfiddle.uk/?rdbms=mysql_8.0&fiddle=3fcfd936d0e10944c012a43621e9d59d). Instead, one could use the `CONCAT` function.

This operator is used in 2d, 3b, 14a, 14b and 14c .

**Comment by dachafra** [comment]
solved
