### ISSUE TITLE
Split report and test case scripts

### ISSUE THREAD

**Issue by pheyvaer** [kg-construct/r2rml-implementation-report#13]
It might be good to split the report and test case scripts in different repos. To be discussed. @dachafra What do you think?

**Comment by andimou** [comment]
(I have no opinion but curiosity 😇 )

 why would you think it would be better to split them?

**Comment by pheyvaer** [comment]
Two different code bases in one repo is not a good idea. The repo is called contains "report" while it also contains scripts to run test cases, which has nothing to do with the report itself.

**Comment by andimou** [comment]
but could you also see them being used independently?

**Comment by pheyvaer** [comment]
Sure, I can generate my own test results without running any of the scripts and still want it to be included in the report. The scripts as just a useful tool for people, not a requirement.

**Comment by dachafra** [comment]
what about ("r2rml-test-cases-support" for the scripts) and this stays as r2rml-implementation report?
In that way, I would also move the "rml-test-cases-support" to this organization: https://github.com/dachafra/rml-test-cases-support, which are basically the same support as for r2rml but in rml test-cases

**Comment by pheyvaer** [comment]
@dachafra Sounds good to me!

**Comment by dachafra** [comment]
@pheyvaer I've just moved all the support to kg-construct/r2rml-test-cases-support so this repo is for you now ;-) Feel free to remove/modify whatever you want

**Comment by pheyvaer** [comment]
Done.
