### ISSUE TITLE
Add testers to R2RML processors table

### ISSUE THREAD

**Issue by pheyvaer** [kg-construct/r2rml-implementation-report#19]

**Comment by dachafra** [comment]
additional to the tester, if there is a row per database+engine, the database should be also included

**Comment by pheyvaer** [comment]
@dachafra It's something like this?

<img width="849" alt="image" src="https://user-images.githubusercontent.com/9413528/135092012-f6fedc23-b2e1-4ebe-80ff-2b1f4d5cd59a.png">

**Comment by dachafra** [comment]
YES!
