### ISSUE TITLE
Idea - a dynamic and interactive report

### ISSUE THREAD

**Issue by tpluscode** [kg-construct/r2rml-implementation-report#2]
Hello @dachafra. Is this is the right place to continue the proposal I started in September?

As reminder, I quickly built an R2RML implementation page which runs in the browser and fetches EARL reports RDFs over the web: https://implementations.r2rml.net

I built it initially for my .NET implementation but with the goal in mind is to have this easily extended with other reports. While it is a static web application, it uses RDF/JS tooling directly in the browser which can allow for dynamism such as filtering (for example by the evaluated platform or RDBMS) and also accommodate various test cases such as those for R2RML and RML alike

I would gladly donate the code, or we could start from scratch with more fine-grained set of requirements. After all it did not take that much work to assemble what I have so far

**Comment by dachafra** [comment]
@tpluscode I think it is a good starting point and really interesting. In the RML implementation report, we used another approach: the engines can add a simple csv with the results by a PR and we generate the EARL report using mappings and an engine (eating our own dog food ;-)). Then we generate a website querying the RDF reports with Comunica and GraphQL-LD. The output is here https://rml.io/implementation-report/ and code: https://github.com/RMLio/rml-implementation-report

I would suggest finding how to merge both approaches in the most efficient way. My requirements at this moment (to be discussed of course) would be:
- Accept PR with the results of the engines
- Automatic generation of the implementation report based on commits in GitHub
- The use of standard technologies that can be adopted/understand by anyone (so we can transfer the report once we don't want to follow its maintenance ;-))

**Comment by dachafra** [comment]
done
