### ISSUE TITLE
Create a separate section per database technology

### ISSUE THREAD

**Issue by dachafra** [kg-construct/r2rml-implementation-report#20]
1 section per RDBMS

**Comment by pheyvaer** [comment]
By when would you like this to be included?

**Comment by dachafra** [comment]
Next meeting? (i.e., 24th May?)

**Comment by pheyvaer** [comment]
Ok, will do!

**Comment by pheyvaer** [comment]
This is the idea right? Still have to add subsections and some text.

![image](https://user-images.githubusercontent.com/9413528/117804618-41753a80-b258-11eb-9f83-03ce2c4cf0e2.png)

**Comment by dachafra** [comment]
YES! 👍 👍 👍 👍

**Comment by dachafra** [comment]
I noticed that table of processors has also changed, RDBMS does not appear. If we can obtain that info in some way I would add it as a new column in the table

**Comment by pheyvaer** [comment]
Well, I would add that in the title of the subsection 😄
