### ISSUE TITLE
Define the configuration file for Walder and metada info

### ISSUE THREAD

**Issue by dachafra** [kg-construct/r2rml-implementation-report#5]
How is the file Walder needs to provide the corresponding info for querying the results?
Additionally, how are we going to obtain the "metadata info" about each engine (e.g, see the image from RML report), it is not available in the results file.

![image](https://user-images.githubusercontent.com/12400271/104002705-b8fb6600-51a1-11eb-9a55-88f4017a103b.png)

**Comment by dachafra** [comment]
One option for the metadata could be: include that info in the config file and generate a set of triples in the results file with that info.

**Comment by pheyvaer** [comment]
I don't really get what you mean. Could you maybe provide an example config file?

**Comment by dachafra** [comment]
this is the current configuration file structured: https://github.com/kg-construct/r2rml-implementation-report/blob/main/test-cases/config.ini

It is used by the script to run the test cases for any type of engine and generate the results in RDF

**Comment by pheyvaer** [comment]
This info should all be in the knowledge graph that every developer publishes.

**Comment by dachafra** [comment]
exactly, it is included in the "results.ttl" file that the scripts generates.
It uses the same workflow as in the RML report, with a [mapping file](https://github.com/kg-construct/r2rml-implementation-report/blob/main/test-cases/mapping.rml.ttl) and the rmlmapper to generate the results.

So we can extend the config file to provide also name, version, test-date and contact information, so the developers only have to modify that file!

**Comment by pheyvaer** [comment]
Nice, so we got that covered then or is there anything else that you mean with this issue?

**Comment by dachafra** [comment]
the developers have also to provide the URL of the generated report.
I assume that they will do it with fork+pull request but I don't know what exactly will be the best way to capture that info as I don't know what Walder needs to be configured.

**Comment by pheyvaer** [comment]
Ooh like that. People need to a line here with the link to the KG in [this example](https://github.com/KNowledgeOnWebScale/walder/blob/development/example/config.yaml#L10).

**Comment by dachafra** [comment]
done
