### ISSUE TITLE
Generate report via Walder

### ISSUE THREAD

**Issue by pheyvaer** [kg-construct/r2rml-implementation-report#8]
We will be using [Walder](https://github.com/KNowledgeOnWebScale/walder) to make the report available. The following things need to happen:

# Steps
- [x] Update the config file to access the knowledge graphs of the test results/EARL reports. 
- [x] Update [the draft](https://github.com/kg-construct/r2rml-implementation-report/blob/main/website/index.html) of the report

# Intermediate steps
- [x] Have example KG with test results for one tool to test locally (check with David)
- [x] Create Walder config file to query results
- [ ] Show results on simple HTML page
- [x] Add extra tool
- [x] Look at layout of HTML page

**Comment by pheyvaer** [comment]
@dachafra Is the second item good for you?

**Comment by dachafra** [comment]
I would say that we should use the W3C CG HTML template, I'll try to find it and upload it to the repo!

**Comment by dachafra** [comment]
here is the first draft: https://kg-construct.github.io/r2rml-implementation-report/

**Comment by pheyvaer** [comment]
@bilalbenma Would it work for you to have a look at this? I would suggest starting with checking out Walder.

**Comment by pheyvaer** [comment]
Hi @bilalbenma 

I wanted to check in to see if you need help with anything. Please let us know!

**Comment by bilalbenma** [comment]
Hi @pheyvaer  
I will start working on the issue this Sunday. I tried to check Walder. I planed to contact you this monday to evaluate the result.

**Comment by pheyvaer** [comment]
@bilalbenma Great! 😄

**Comment by dachafra** [comment]
@jatoledo could you provide a raw link to the Morph-RDB EARL report?

**Comment by jatoledo** [comment]
EARL report :
https://raw.githubusercontent.com/jatoledo/r2rml-implementation-report/main/test-cases/results.ttl

**Comment by pheyvaer** [comment]
Hi @bilalbenma, I wanted to check in to see how it's going with Walder. At what step are you at the moment? Do you need any help?

**Comment by dachafra** [comment]
can we close this? I think we finish it :-)
